name: "pipeline"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: yarn 

      - name: Build
        run: yarn build

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

  run_lint:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

  deploy:
    needs: [build, run_tests, run_lint]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/
      
      - name: Install Netlify cli
        run: |
          npm install netlify-cli@10.1.0 -g

      - name: Deploy to netlify
        run: |
          netlify deploy --dir=prod --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.TEAM_5_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
