name: "pipeline"
on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

  run_tests:
    needs: [build_linux]
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

  deploy:
    needs: [build_linux, run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/
      
      - name: Install Netlify cli
        run: |
          npm install netlify-cli@10.1.0 -g

      - name: Deploy to netlify
        run: |
          netlify deploy --dir=prod --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.TEAM_8_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
