name: "pipeline"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --prefer-offline

      - name: Build
        run: yarn build
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --prefer-offline

      - name: Run tests
        run: yarn test

  run_lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --prefer-offline

      - name: Lint
        run: yarn lint

  deploy:
    needs: [build, run_tests, run_lint]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: build/
          
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: netlify-cli
          restore-keys: netlify-cli-

      - name: Install Netlify cli
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install netlify-cli@10.1.0 -g

      - name: Deploy to netlify
        run: |
          netlify deploy --dir=build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.TEAM_5_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
