name: "pipeline"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add react scripts and netlify
        run: yarn add --dev react-scripts netlify-cli@10.1.0

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Deploy to netlify
        run: |
          netlify deploy --dir=build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.TEAM_4_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
