name: "pipeline"
on: push

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-build
          path: build/

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac-build
          path: build/

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: yarn build

  run_tests:
    needs: [build_windows, build_macos, build_linux]
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn tset

  run_lint:
    needs: [build_windows, build_macos, build_linux]
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

  deploy:
    needs: [build_windows, build_macos, build_linux, run_tests, run_lint]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/
      
      - name: Install Netlify cli
        run: |
          npm install netlify-cli@10.1.0 -g

      - name: Deploy to netlify
        run: |
          netlify deploy --dir=prod --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.TEAM_3_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
